version: "3"

services:
  app:
    build:
      context: .
    ports:
      - '8090:8090'
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8090"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=dag_sample
      - DB_PASS=dag_sample
    depends_on:
      - db
  db:
    image: mariadb:10.4
    ports:
      - '3308:3308'
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=dag_sample
      - MYSQL_PASSWORD=dag_sample
      - MYSQL_ROOT_PASSWORD=dag_sample
